
import { GlobalAttributes } from "../interfaces";
import { randomUUID } from "crypto";


/**
    * Global attributes and event handlers for testing purposes.
*/

export const globalAttributes: GlobalAttributes = {
    accessKey: randomUUID(),
    autoCapitalize: "sentences",
    className: randomUUID(),
    contentEditable: "inherit",
    dir: "rtl",
    draggable: Math.random() < 0.5,
    hidden: Math.random() < 0.5,
    id: randomUUID(),
    lang: randomUUID(),
    slot: randomUUID(),
    spellCheck: true,
    tabIndex: 1,
    title: randomUUID(),
    translate: Math.random() < 0.5,
    onabort: null,
    onauxclick: null,
    onblur: null,
    oncancel: null,
    oncanplay: null,
    oncanplaythrough: null,
    onchange: null,
    onclick: null,
    onclose: null,
    oncontextmenu: null,
    oncopy: null,
    oncuechange: null,
    oncut: null,
    ondblclick: null,
    ondrag: null,
    ondragend: null,
    ondragenter: null,
    ondragleave: null,
    ondragover: null,
    ondragstart: null,
    ondrop: null,
    ondurationchange: null,
    onemptied: null,
    onended: null,
    onerror: null,
    onfocus: null,
    onformdata: null,
    ongotpointercapture: null,
    oninput: null,
    oninvalid: null,
    onkeydown: null,
    onkeypress: null,
    onkeyup: null,
    onload: null,
    onloadeddata: null,
    onloadedmetadata: null,
    onloadstart: null,
    onlostpointercapture: null,
    onmousedown: null,
    onmouseenter: null,
    onmouseleave: null,
    onmousemove: null,
    onmouseout: null,
    onmouseover: null,
    onmouseup: null,
    onpaste: null,
    onpause: null,
    onplay: null,
    onplaying: null,
    onpointercancel: null,
    onpointerdown: null,
    onpointerenter: null,
    onpointerleave: null,
    onpointermove: null,
    onpointerout: null,
    onpointerover: null,
    onpointerup: null,
    onprogress: null,
    onratechange: null,
    onreset: null,
    onresize: null,
    onscroll: null,
    onsecuritypolicyviolation: null,
    onseeked: null,
    onseeking: null,
    onselect: null,
    onselectionchange: null,
    onselectstart: null,
    onstalled: null,
    onsubmit: null,
    onsuspend: null,
    ontimeupdate: null,
    ontoggle: null,
    onvolumechange: null,
    onwaiting: null,
    onwheel: null
};
  